# NAS section is currently commented out because of lack of source but this will soon exist.
version: '3.8'

services:
  llm_server:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  rag_engine:
    build: ./rag_engine
    ports:
      - "8001:8001"
    volumes:
      - ./local_rag_data:/app/data
      # - nas_data:/app/nas_data  # Uncomment to enable NAS later
    depends_on:
      - vector_db
      - llm_server

  vector_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  rag_ui:
    build: ./rag_ui
    ports:
      - "8501:8501"
    depends_on:
      - rag_engine

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  # uptime_kuma:
  #   image: louislam/uptime-kuma
  #   ports:
  #     - "3001:3001"

  # nas_mount:
  #   image: alpine
  #   command: tail -f /dev/null
  #   volumes:
  #     - nas_data:/mnt/nas  # For CIFS/NAS mount, configure in future

volumes:
  ollama_data:
  qdrant_data:
  grafana_data:
  # nas_data:  # Uncomment to enable NAS volume
